### ISSUE TITLE
Incorrect JSON URL in readme and json

### ISSUE THREAD

**Issue by Drakonas** [jayp76/MiSTer_get_optional_installers#1]
The link to the JSON in the Readme for the downloader.ini and the json file itself expects the json to be in the misc directory, but it's in the root.

```
[get_yarmus]
db_url = https://raw.githubusercontent.com/jayp76/MiSTer_get_optional_installers/master/misc/get_yarmus.json
```

This should be the correct text to place, and needs to be adjusted in the json file as well:
```
[get_yarmus]
db_url = https://raw.githubusercontent.com/jayp76/MiSTer_get_optional_installers/master/get_yarmus.json
```
Without this fixed, downloader.ini fails to pull the json properly.

**Comment by jayp76** [comment]
Thank you for pointing this. Should be fixed now.
